mirleft/ocaml-tls

CHANGES.md
lib/config.ml
tests/interop-openssl-sclient.sh
tests/interop-openssl-sserver.sh

disable RC4 by default (users who need RC4 can tweak the configuration)
fixes #8

do not advertise RC4

---

CHANGES.md
lib/config.ml
lib/config.mli
lib/core.ml
lib/handshake_client.ml
lib/handshake_common.ml
lib/handshake_server.ml
lib/reader.ml
lib/reader.mli
lib/state.ml
lib/writer.ml
lib/writer.mli
lwt/examples/echo_client.ml
lwt/examples/echo_server.ml

this builds on top of SNI! It might not yet be ready for merging (esp. the modification to echo_client should not be merged). any comments are welcome (addresses first half of #171)

Client authentication

---

lib/handshake_common.ml

The other part of https://github.com/mirleft/ocaml-x509/pull/39.

Use the now-manifest x509.authenticator type

---

lib/config.ml
lib/config.mli

No more harm than having non-quite-bijective serialization for `config` that's already there.

Add `with sexp` to `client` and `server`

---

mirage/tls_mirage.ml

Don't touch `Io_page` directly, assume any `Cstruct.t` can be sent over TCP.
Adds compatibility with recent `io-page` too; breaks compatibility with `mirage-net-xen` < 1.3.0 (before https://github.com/mirage/mirage-net-xen/commit/7d2777d789530e2104b6d9252cdca0d6f8078acb).

Remove manual Io_page juggling

---

mirage/tls_mirage.ml
mirage/tls_mirage.mli

Add `epoch` projection to `tls.mirage` interface; mirrors the one in `tls.lwt`.

Mirage: expose Epoch

---

lib/engine.ml

just installed new crypto keys, but the handshake was not yet
authenticated (finished message was not yet received)
(credits go to karthik during real world crypto)

prevent application data to be sent and received if a handshake

---

lib/engine.ml
lib/handshake_client.ml
lib/handshake_server.ml

we can still reproduce the internal states:
- the outgoing state (state-out) is always recorded
- the initial state not recorded (it is known at the beginning, and the same as the last outgoing state)
- handshake-in/handshake-out is not recorded (the raw packets are recorded and thus these can be reproduced)
--> tracing of handshake packets was primarily useful for visualization in the demonstration server, but not for trace checking
the amount of producde data is reduced by roughly 50%...

remove duplicated traces

---

lib/engine.ml

otherwise, split will raise an invalid_argument exception
(impact on pinata: doesn't hand out secrets, but aborts (exception is thrown and caught) the connection)

check that the given buffer length is >= size + 4

---

lib/config.ml
lib/config.mli
lib/handshake_client.ml
lib/handshake_server.ml
lwt/examples/http_client.ml

not requiring this leaves us otherwise open to MITM prefix
attacks.  RFC5746 is out since > 5 years.  no reason to allow
the insecure option.

always require secure renegotiation

---

mirage/example/unikernel.ml
mirage/tls_mirage.ml
mirage/tls_mirage.mli
opam

this includes/supersedes #225 -- and reports a proper error to the user

Mirage 2.3.0

---

lib/packet.ml

https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml
Update TLS extension ID enum and RFC/draft comments.
This brings the list here up-to-date with the current IANA registry. This just adds the values; it doesn't actually do anything with them. The /rfc dir needs updating with RFC text as well.

update extension_type enum

---

lwt/tls_lwt.ml
lwt/tls_lwt.mli

instead of eagerly closing file descriptors in error conditions,
behave in a unsurprising way: never close any file descriptors
which have been passed in.  Provide both close_tls and close
functions for terminating connections.
The function of_t now has an optional argument ?close, which by
default closes the underlying connection.
Thus, the lifecycles of file descriptors is streamlined with the
Lwt_unix interface: whenever an error occurs, the caller is
supposed to close the connection.
The only exception is accept and connect if serer_of_fd/client_of_fd
fails the TLS upgrade -- here the newly allocated file descriptor is
silently closed.  This prevents fd leakage, since the fd is not
exposed to a user.

no close of passed in file descriptors

---

lib/ciphersuite.ml
lib/config.ml
lib/config.mli

(actually, a better name is `key erasure` (djb))

rename pfs to fs -- there's nothing perfect in forward secrecy

---

design.md
lwt/examples/echo_client.ml
lwt/examples/echo_server.ml
lwt/examples/echo_server_sni.ml
lwt/examples/http_client.ml
lwt/examples/starttls_server.ml
lwt/examples/test_client.ml
lwt/examples/test_server.ml
lwt/tls_lwt.ml

Since the previous design was untenable, I made sure entropy init is actually completed *synchronously* ([docs](https://github.com/mirleft/ocaml-nocrypto/blob/master/lwt/nocrypto_entropy_lwt.mli#L10)). This means that we can **FINALLY** internalize entropy init and people can just forget about the whole thing.

Implied entropy for Lwt

---

lib/config.ml
lib/config.mli
lib/core.ml
lib/engine.ml
lib/handshake_client.ml
lib/handshake_common.ml
lib/handshake_crypto.ml
lib/handshake_crypto.mli
lib/handshake_server.ml
lib/state.ml
mirage/example2/config.ml

This adds support for session resumption. The user-facing change is that both `Config.client` and `Config.client` have a callback parameter `session_cache : Cstruct.t option -> epoch_data option`. A client uses the session id from `session_cache None` in its initial client hello. A server resumes a session if the id is found in the cache.
The cache may be filled by a user by using the `epoch_data` (exposed from `Engine.epoch : state -> epoch_data`) and inserting it into a cache, using its `sessionid` as key.
Internal cleanups: `epoch_data` moved to `Core` module; `Handshake_crypto` has `derive_master_secret` and `initialise_crypto_context` separated. Bot the client and the server state machine have two new states, waiting for CCS/Finished from the other side during resumption. Both …

Session resumption

---

lib/core.ml
lib/engine.ml
lib/handshake_client.ml
lib/handshake_common.ml
lib/handshake_crypto.ml
lib/handshake_crypto.mli
lib/handshake_server.ml
lib/reader.ml
lib/state.ml
lib/writer.ml
rfc/rfc7627.txt

based on resumption #283 an implementation of session hash (proposed draft). resumption is only possible if an extended_master_secret was used (due to triple handshake the only sensible way to deal with it)

Session hash

---

lib/core.ml
lib/engine.ml

Expose `client_random` and `server_random` from `lib/state.ml` to allow extracting the authenticated timestamp from a remote party:
```ocaml
type session_data = {
server_random    : Cstruct.t ; (* 32 bytes random from the server hello *)
client_random    : Cstruct.t ; (* 32 bytes random from the client hello *)
(* [...] *)
}
```
in `epoch_data` as `own_random` and `peer_random`, see `lib/engine.mli` ->
```ocaml
val epoch : (state : State.state) -> (epoch : epoch_data)`

expose own_random and peer_random in epoch_data

---

lib/engine.ml
lib/engine.mli
lwt/tls_lwt.ml
mirage/tls_mirage.ml

The RFC is loose what to do here, but best practises (other stacks) block
while renegotiation is in progress.  This is especially important for triple
handshake attack, more to be read in the thread on the IETF TLS WG
https://www.ietf.org/mail-archive/web/tls/current/msg18313.html .
This also removes the `handshake_in_progress`, which was unused, and considering that `can_handle_appdata` is provided, this should be sufficient.

block while renegotiation is in progress, fixes #140

---

mirage/example/sekrit/ca-roots.crt
mirage/example/sekrit/server.key
mirage/example/sekrit/server.pem
mirage/example/sekrit/tls/ca-roots.crt
mirage/example/sekrit/tls/server.key
mirage/example/sekrit/tls/server.pem
mirage/example2/sekrit/server.key
mirage/example2/sekrit/server.pem
mirage/example2/sekrit/tls/server.key
mirage/example2/sekrit/tls/server.pem
mirage/tls_mirage.ml

this is certainly a breaking API change and all earlier mirage applications
will break, but forcing a "tls/" path in the store is imho bad.

do not hardcode path to certificates and private keys ("tls/"), fixes #294

---

lib/core.ml
lib/engine.ml
lib/handshake_client.ml
lib/handshake_common.ml
lib/handshake_server.ml
lib/state.ml

- returned failures are different
- preserve more in the epoch_data:
- peer_certificate (t option)
- received_certificates (t list)
- peer_certificate_chain (t list)
- trust_anchor (t option)

X.509 updates for path building:

---

lib/handshake_client.ml
lib/handshake_server.ml

previously, this was only allowed if the extended master secret was provided
(followup of #300, which includes reasoning)

allow resumption if either no renegotiation OR extended master secret

---

lib/engine.ml
lib/handshake_client.ml
lib/handshake_client.mli
lib/handshake_server.ml
lib/handshake_server.mli
lib/state.ml

- allows handshake to modify decryptor (required for TLS 1.3)

unify return type of hanshake and ccs

---

lib/core.ml
lib/engine.ml
lib/handshake_client.ml
lib/handshake_common.ml
lib/handshake_server.ml
lib/reader.ml
lib/writer.ml
tests/readertests.ml
tests/readerwritertests.ml
tests/testlib.ml
tests/writertests.ml

e.g. a server must not sent any Hostname extension with an actual name, a client must sent some name in their Hostname extension.  A server may not send a SignatureAlgorithms extension, ...
This is a preparation for 1.3, where they differ even more (KeyShare of keyshareentry list vs KeyShare of keyshare ; PreSharedKey of psk_id list vs PreSharedKey of psk_id)

Separate client and server extensions

---

mirage/example/config.ml
mirage/example/unikernel.ml

I kept the second example the way it was. It seems to not be too flexible anyway in terms of target architecture.

use functoria style for mirage example

---

_oasis
mirage/tls_mirage.ml
mirage/tls_mirage.mli
opam

I massaged the commits of #329 slightly: no need for `ptime` in `tls-lwt` right now, and add a dependency onto `ptime >= 0.8.1` (for `Ptime.v`) into the opam file.  This is only needed for the mirage subpackage, but we're not able to express this in opam (we could explicit create multiple packages (might be worth doing, but then we should also switch to `topkg`), or provide a new `mirage-no-mirage` (similar to `mirage-no-xen`/`mirage-no-solo5`) package (feels way to hacky)).
Travis CI will not succeed with mirage since it uses mirage as released into opam-repository (and I don't think there's much value in moving this towards mirage-dev branches).  Likely the example unikernels suffer from bitrot atm, but can be fixed in subsequent commits.
@mattgray I squashed your commits and amended …

Use PCLOCK / Ptime

---

lwt/tls_lwt.ml
lwt/tls_lwt.mli
mirage/example/unikernel.ml
mirage/tls_mirage.ml
mirage/tls_mirage.mli

This is the low-level interface, and not all TLS scenarios require any form of name validation.
An example is a syslog server, we don't want to depend on DNS for syslog.  Authentication is done via a CA chain, but no name is compared.  See https://github.com/hannesm/logs-syslog/blob/32137a34e83e5a0ba6ba8c6e8da45957971de71e/src/logs_syslog_lwt.ml#L65

don't require a peer name for client_of_fd, there's no need for this

---

.merlin
.travis-test-mirage.sh
.travis.yml
_tags
mirage/example/config.ml
mirage/example/unikernel.ml
mirage/example2/config.ml
mirage/example2/unikernel.ml
mirage/tls_mirage.ml
mirage/tls_mirage.mli
opam
pkg/META

this is #349 with minor stylistic modifications, and an attempt to make travis happy (by not pinning nocrypto/x509/asn1)

Samoht errors

---

lwt/tls_lwt.ml

Prevents failure when the user calls `Lwt_io.close` on both `ic` and `oc`.

do not crash on double close

---

lib/config.ml
lib/config.mli
lib/handshake_server.ml

The code for acceptable certificate authorities in a client certificate
request was already implemented, but handshake_server.ml had hardcoded
an empty list of CAs. This commit adds a configuration option for this.
this is #332 rebased (and amended) on master.  it also uses `X509.distinguished_name list` instead of `X509.t list` (and thus needs X509 master which provides the sexp conversion of `distinguished_name`) and renames `accepted_cas` to `acceptable_cas`.

Implement server acceptable certificate auths

---

myocamlbuild.ml
opam
pkg/META.in

this applies the same trick as nocrypto for figuring out runtime dependencies of ppx_sexp_conv, and thus allows interoperability with recent releases (v0.11.x series apart from .0 which has a runtime dependency on base)

compatibility with ppx_sexp_conv > v0.11.0

---

lib/handshake_common.ml
pkg/pkg.ml

this fixes interoperability with (at least) android 4.4 devices

lib: do not require the list of ciphersuites sent by the client to be a proper set

---

CHANGES.md
lwt/tls_lwt.ml

previously, if handle_tls returned a response to the peer, write was called,
which may error out (recording it's error in the state and Lwt.fail). the
received data was never returned to the caller.
now, similar to the semantics in tls_mirage, the error from write is only
recorded in the state, and returned on the next function call (write/..).
should fix #347, alternative to #371, #387 -- could you please test this @edwintorok @anmonteiro @rymdhund //cc @pqwy

Tls_lwt: delay error from writing to peer while reading.

---

.merlin
.travis.yml
_tags
lib/control.ml
lib/core.ml
lib/engine.ml
lib/reader.ml
lib/reader.mli
lib/state.ml
lib/tracing.ml
mirage/example2/config.ml
mirage/tls_mirage.ml
mirage/tls_mirage.mli
opam
pkg/META.in
tests/readertests.ml
tests/readerwritertests.ml

- support for cstruct 4.0.0+
- remove support for < 4.04.2 (same as x509 in master)
- remove result (part of 4.03.0)
- enhance mirage/example2 to work on more platforms than unix

plumbing for the next release

---

.travis.yml
CHANGES.md
_tags
lib/config.ml
lib/config.mli
lib/core.ml
lib/engine.ml
lib/engine.mli
lib/handshake_client.ml
lib/handshake_common.ml
lib/handshake_server.ml
lib/state.ml
lwt/examples/http_client.ml
lwt/examples/starttls_server.ml
lwt/tls_lwt.mli
lwt/x509_lwt.ml
lwt/x509_lwt.mli
mirage/tls_mirage.ml
mirage/tls_mirage.mli
opam
pkg/META.in
tests/feedback.ml

this is a minimal set of changes for the new X509 API. orthogonal changes (such as removing Tracing/sexp/switiching build system/use Domain_name.t instead of string) can be addressed separately

adapt to X509 0.7.0 API

---

.travis.yml
_tags
lib/config.ml
lib/handshake_client.ml
lib/handshake_server.ml
lwt/examples/http_client.ml
lwt/x509_lwt.ml
lwt/x509_lwt.mli
mirage/tls_mirage.ml
mirage/tls_mirage.mli
opam

addresses some points of #399 and adapts to the new x509 API. on top of #403

X509.0.9.0: hash_whitelist and expose crl support

---

_tags

I'm not sure how this could've ever worked (the META for the lwt subpackage already contains the nocrypto.lwt dependency).

tls.lwt uses nocrypto.lwt (to seed the RNG), record this dependency in _tags

---

lib/handshake_server13.ml

When using `logs` through a parent application like `opium`, cipher and group information would appear for every new connection established. When log level is set to info, 95% of the logs would be about cipher and group. It seems a good idea to restrict the scope of this information to `debug`.

Demote group/cipher logging to DEBUG

---

lib/crypto.ml

Due to the introduction of `Cstruct.length` and `let open Cstruct in`, we must rename `length` to `v_length`.

Rename length to v_length to be compatible with cstruct.6.0.0

---

lib/utils.ml

OCaml 4.12 added `List.compare` and now shadows `Pervasives.compare` in these particular contexts.

Add support for OCaml 4.12

---

lib/config.ml
lib/config.mli
lib/core.ml
lib/engine.ml
lib/engine.mli
lib/reader.mli
lib/state.ml

[@@deriving sexp_of] seems like the more appropriate ppx to use given many of the types in lib/ can't be deserialized.
This would avoid confusion like https://github.com/mirleft/ocaml-tls/pull/398 where it's unclear if a state can be restored from an S-expression.

Use sexp_of ppx and remove unnecessary t_of_sexp stubs

---

async/dune
async/examples/dune
async/examples/test_client.ml
async/examples/test_server.ml
async/io.ml
async/io.mli
async/io_intf.ml
async/session.ml
async/session.mli
async/tls_async.ml
async/tls_async.mli
tls-async.opam

I'd like to offer an Async I/O implementation for Ocaml_tls. This is heavily cribbed from the existing Lwt implementation and is offered as a I/O-agnostic functor similar to cohttp.
I'm not familiar enough with Lwt to port that code over but I believe it should be relatively straightforward for someone more familiar with Lwt.
A test client and echo server are provided in an example subdirectory.
I believe this PR supersedes https://github.com/mirleft/ocaml-tls/pull/355, which doesn't appear to be actively developed.
Credit to @dinosaure  for authoring https://github.com/janestreet/ocaml-tls/pull/1 which was used for inspiration and provided some Async IO code.

Async implementation, including examples

---

async/dune
async/examples/test_server.ml
async/session.mli
async/tls_async.ml
async/tls_async.mli
async/x509_async.ml
async/x509_async.mli
tls-async.opam

This is a subset of the changes proposed in https://github.com/mirleft/ocaml-x509/pull/150. At a high level:
* `Cstruct.t` is replaced with `contents:string` for various decode functions
* ``('a, [ `Msg of string ])`` result is replaced with `'a Or_error.t`
* `of_pem_file` and `of_pem_dir` functions are provided where it's useful to go from a `Filename.t -> t` or `t list`
* [Authenticator] gets a [Param] submodule to facilitate constructing an `Authenticator.t` where I/O is required
This Pull Request doesn't include the sexplib or `to_string` opinions proposed in https://github.com/mirleft/ocaml-x509/pull/150 as they're relatively easy to inline.
The example server test_server.ml is updated to use the new call sites.

Add x509-async module

---

async/dune
async/x509_async.ml
tls-async.opam

I propose we remove the single invocation of [Async_find] in [X509_async] to drop the dependency.
This also has the nice property of truing up the Async version with the existing Lwt version by dropping support for nested directory structures.

Drop dependency on Async_find

---

async/examples/dune
async/examples/test_client.ml
async/examples/test_server.ml
async/tls_async.ml
tls-async.opam

This PR updates to version 0.15 of the JS open source OCaml packages and fixes the build accordingly.

Upgrade to 0.15 of Jane Street packages

---

eio/tls_eio.ml
eio/x509_eio.ml
tls-eio.opam

I introduced this bug in f32809976cdf03c19ade77 (not in the history due to squash merge). However, setting the state to `Eof` is not the same as reporting end-of-file to the user, and we may still have data to report. This can cause us to miss data at the end of the stream in some cases.

tls-eio: Fix end-of-file handling

---

eio/tests/dune
eio/tests/fuzz.ml
eio/tests/mock_socket.ml
eio/tests/mock_socket.mli
eio/tests/test_rng.ml
eio/tls_eio.ml
tls-eio.opam

The test picks two random strings, one for the client to send and one for the server. It then runs a send and receive fiber for each end.
A dispatcher fiber then sends commands to these worker fibers. It may:
- Ask a send fiber to send some plaintext from the message.
- Ask a receive fiber to read some plaintext.
- Ask the network to transmit some number of bytes in some direction.
- Ask a send fiber to shut down the connection.
- Yield (allowing the workers to make progress).
At the end, it asks any remaining send fibers to shut down, allows all network traffic to be transmitted, and waits for the receive fibers to end. It then checks that the receiver got everything that was sent (with a special case to avoid reporting errors due to #452).
By default, this just runs a few random …

tls-eio: add fuzz tests using crowbar

---

eio/tests/dune
eio/tests/fuzz.ml
eio/tests/mock_socket.ml

These are the improvements to the fuzz tests that were part of #459. I think it's worth merging these on their own, since that PR isn't ready.
- The mock_socket has changed slightly. Previously, it would request a size to read, do the read, and then wait for another size for the next read, which would typically just be the EOF for that request. This made it harder for the fuzzer to reach useful states. Now you can do a single transmit with a single test action.
- ~Simplified the write in Tls_eio slightly by using the new `Flow.write` operation.~
- Only log a send when we actually send some data.
- Allow the fuzzer to perform all the actions needed for the Tls handshake in one go instead of requiring it to find them by searching. This provides it a way to get to the interesting cases …

tls-eio: improve fuzz tests

---

lwt/tls_lwt.ml

as discussed in #464 (thanks to @talex5 for raising this)

tls-lwt: do not catch out of memory exception

---

eio/tests/fuzz.ml
eio/tests/mock_socket.ml
eio/tests/mock_socket.mli
eio/tls_eio.ml
eio/tls_eio.mli
tls-eio.opam

(note: this looks long, but most of the changes are to the fuzz tests)
The changes to tls-eio.ml are:
- Add new `Tls_socket_closed` error. Writing to a closed connection previously reported end-of-file, which isn't quite right.
- Replace the object types with non-object types.
- Rename `read` to `single_read`, `write` to `single_write`, and `copy_from` to `copy`, to match the Eio 0.12 API.
- `copy` now uses an Eio helper that just calls `single_write`.
This removes all uses of objects from `tls-eio.ml`.

Update to Eio 0.12

---

lib/core.ml
lib/engine.ml
lib/engine.mli
lib/handshake_client13.ml
lib/handshake_common.ml
lib/handshake_crypto.mli
lib/handshake_server13.ml
lib/state.ml
lwt/examples/echo_client.ml
lwt/examples/resume_echo_server.ml

Support exporter secrets, as defined in RFC 5705 & 8446

---

CHANGES.md
async/io.ml
eio/tls_eio.ml
lib/engine.ml
lib/engine.mli
lwt/tls_lwt.ml
mirage/tls_mirage.ml

Engine.epoch: return a result instead of a custom polymorphic variant

---

eio/tests/mock_socket.ml
eio/tests/mock_socket.mli
eio/tests/tls_eio.md
eio/tls_eio.ml
eio/tls_eio.mli

After shutting down the TLS flow, I would like to close the underlying TCP socket.  This is of course handled by the switch, but since I'm using resource pooling, I would like to do this before leaving the scope of the switch.  I could pass around the TCP flow along with the TLS flow, but this breaks the flow-abstraction which is very useful when dealing with TLS.
My proposal here is the the TLS flow implements the close interface but falls back to no-op if the underlying flow does not implement it.  We could consider making close a requirement for the underlying flow, since it should be possible to amend a no-op close operation to an existing flow in the (unlikely?) event that a non-TCP flow is used.
(I made a [hack](https://github.com/paurkedal/ocaml-caqti/commit/6f24b835e311488c0cbfaeb4 …

Implement Eio.Resource.Close

---

lib/engine.mli

As discussed in https://github.com/robur-coop/miragevpn/pull/234/files/4f553471dc81e03790ead342caba5e50ac05fd71#r1576424941

Document why Tls.Engine.send_application_data is None

---

tls-async.opam
tls-eio.opam
tls-lwt.opam
tls-mirage.opam
tls.opam

- mirage-crypto* < 1.0.0
- hkdf < 2.0.0
The upper-bounds are taken from the opam-repository.

Update upper bounds on mirage-crypo and hkdf

---

async/examples/dune
lwt/examples/dune
tests/dune
tests/feedback.ml
tests/server.key
tests/server.pem
tls-async.opam
tls.opam

- fix feedback to finish the handshake until server and client are ready Previously, it was only waited until client is ready. This in not sufficient for the TLS 1.3 state machine. In TLS < 1.3, the server sends a final "Finished" message, while in TLS 1.3, the client sends the final "Finished" message. In feedback operations, this was dropped, leading to MAC mismatch.
- tests/server.{key,pem} are symbolic links to ../certificates/server.{key,pem}
- tests/feedback.exe is run as test now
- tests/feedback.exe uses cmdliner and logs now
//cc @dinosaure this fixes feedback for the current main branch. I'll soon rebase the #497 PR on top of this to figure out whether this is fixed then there as well.

tests/feedback: fix for TLS 1.3, run as test

---

async/tls_async.ml
async/tls_async.mli
lwt/examples/dune
lwt/examples/tls_over_tls.ml
lwt/tls_lwt.ml
lwt/tls_lwt.mli

With @MisterDA , we have a use-case which requires TLS tunneling over an existing TLS connection. This should be pretty easy, but the current `tls-lwt` API only allow TLS negotiation over an `Lwt_unix.file_descr` which limits our ability to use an existing TLS connection as the carrier. This PR adds a new `Tls_lwt.Unix.client_of_channels` function to establish the TLS over input/output `Lwt_io.channel` instead, which were potentially created by a previous TLS.
To explain why TLS-over-TLS is useful, I've attached an example to show how HTTPS proxying work:
- The client first does an HTTPS request to the proxy, and ask it to `CONNECT to_some_server.net:443`
- The proxy hopefully responds with a `200 OK` success code after connecting to the server
- From there, the TLS connection with the …

TLS over an existing connection

---

lwt/tls_lwt.ml
lwt/tls_lwt.mli

useful e.g. in albatross where we may have partial reads.

tls-lwt: read add an optional ?off argument

---

miou/tls_miou_unix.ml

Spotted by caqti, this patch fix the recursion of read_in and keep the offset and the length calculated along the recursion even if, at the beginning, they are optional arguments.

Fix the recursion of Tls_miou_unix.read_in

---

lib/crypto.ml
lib/engine.ml

previously, we had a nearly exponential blowup at the border of 1 lsl 14 where the data was cut into pieces (but we still hold our hands at the old data)

allocate less: the case where huge data is sent via send_application_data

---

lib/packet.ml

This alert is sent by chromium on self-signed certificates, so it probably makes sense to have a useful error message, as opposed to "TLS alert from peer: unknown 46"

put CERTIFICATE_UNKNOWN back

---

miou/tls_miou_unix.ml
tls.opam
unix/dune
unix/tls_unix.ml
unix/tls_unix.mli

This is an updated version of https://github.com/mirleft/ocaml-tls/pull/443 rebased on top of master.
I then took the current `tls-miou` implementation and replaced `Miou_unix` by `Unix`

Add an unix implementation of TLS
